package com.x1colegal.materialyt

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Base64
import android.webkit.JavascriptInterface
import android.webkit.WebChromeClient
import android.webkit.WebView
import org.json.JSONArray
import org.json.JSONObject
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.services.youtube.InnertubeClientRequestInfo
import org.schabi.newpipe.extractor.services.youtube.PoTokenProvider
import org.schabi.newpipe.extractor.services.youtube.PoTokenResult
import org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper
import java.time.Instant
import java.util.concurrent.CompletableFuture
import java.util.concurrent.TimeUnit

/** Supplies NewPipe Extractor with WEB PoTokens generated by a local BotGuard WebView. */
object NewPipePoTokenProvider : PoTokenProvider {
    private val lock = Any()
    private var runtime: BotGuardRuntime? = null
    private var visitorData: String? = null
    private var streamingToken: String? = null

    fun reset() = synchronized(lock) {
        runtime?.close()
        runtime = null
        visitorData = null
        streamingToken = null
    }

    override fun getWebClientPoToken(videoId: String): PoTokenResult? = runCatching {
        synchronized(lock) {
            var current = runtime
            if (current == null || current.expired()) {
                current?.close()
                val requestInfo = InnertubeClientRequestInfo.ofWebClient().also {
                    it.clientInfo.clientVersion = YoutubeParsingHelper.getClientVersion()
                }
                visitorData = YoutubeParsingHelper.getVisitorDataFromInnertube(
                    requestInfo, NewPipe.getPreferredLocalization(), NewPipe.getPreferredContentCountry(),
                    YoutubeParsingHelper.getYouTubeHeaders(), YoutubeParsingHelper.YOUTUBEI_V1_URL,
                    null, false
                )
                current = BotGuardRuntime(MaterialYtApp.instance.applicationContext)
                current.initialize()
                streamingToken = current.mint(visitorData!!)
                runtime = current
            }
            PoTokenResult(visitorData!!, current.mint(videoId), streamingToken)
        }
    }.onFailure { AppLog.failure("NewPipe PoToken", it) }.getOrNull()
}

private class BotGuardRuntime(private val context: Context) {
    private val main = Handler(Looper.getMainLooper())
    private val ready = CompletableFuture<Unit>()
    private val mintResults = mutableMapOf<String, CompletableFuture<String>>()
    private var webView: WebView? = null
    private var expiresAt = Instant.EPOCH

    fun initialize() {
        main.post {
            val view = WebView(context)
            webView = view
            view.settings.javaScriptEnabled = true
            view.settings.blockNetworkLoads = true
            view.settings.userAgentString = USER_AGENT
            view.webChromeClient = WebChromeClient()
            view.addJavascriptInterface(Bridge(), "MaterialYtPoToken")
            val html = context.assets.open("po_token.html").bufferedReader().use { it.readText() }
                .replace("</script>", "\nMaterialYtPoToken.pageReady()</script>")
            view.loadDataWithBaseURL("https://www.youtube.com", html, "text/html", "utf-8", null)
        }
        ready.get(30, TimeUnit.SECONDS)
    }

    fun mint(identifier: String): String {
        val result = CompletableFuture<String>()
        synchronized(mintResults) { mintResults[identifier] = result }
        val quoted = JSONObject.quote(identifier)
        val bytes = identifier.toByteArray().joinToString(",") { (it.toInt() and 0xff).toString() }
        main.post { webView?.evaluateJavascript("""
            try {
              const id=$quoted, out=obtainPoToken(webPoSignalOutput, integrityToken,new Uint8Array([$bytes]));
              MaterialYtPoToken.token(id,Array.from(out).join(','));
            } catch(e) { MaterialYtPoToken.error($quoted,String(e)); }
        """.trimIndent(), null) }
        return result.get(20, TimeUnit.SECONDS)
    }

    fun expired(): Boolean = Instant.now().isAfter(expiresAt)

    fun close() = main.post {
        webView?.apply { loadUrl("about:blank"); removeAllViews(); destroy() }
        webView = null
    }

    private inner class Bridge {
        @JavascriptInterface fun pageReady() = Thread {
            runCatching {
                val challenge = request(CREATE_URL, "[\"$REQUEST_KEY\"]")
                val jsData = parseChallenge(challenge)
                main.post { webView?.evaluateJavascript("""
                    try { data=$jsData; runBotGuard(data).then(r=>{
                      webPoSignalOutput=r.webPoSignalOutput;
                      MaterialYtPoToken.botguard(r.botguardResponse);
                    }).catch(e=>MaterialYtPoToken.initError(String(e)));
                    } catch(e) { MaterialYtPoToken.initError(String(e)); }
                """.trimIndent(), null) }
            }.onFailure(ready::completeExceptionally)
        }.start()

        @JavascriptInterface fun botguard(response: String) = Thread {
            runCatching {
                val generated = JSONArray(request(GENERATE_URL, JSONArray().put(REQUEST_KEY).put(response).toString()))
                val token = decodeBase64(generated.getString(0)).joinToString(",") { (it.toInt() and 0xff).toString() }
                expiresAt = Instant.now().plusSeconds((generated.optLong(1, 3600) - 600).coerceAtLeast(60))
                main.post { webView?.evaluateJavascript("integrityToken=new Uint8Array([$token])") { ready.complete(Unit) } }
            }.onFailure(ready::completeExceptionally)
        }.start()

        @JavascriptInterface fun token(identifier: String, bytes: String) {
            val encoded = Base64.encodeToString(bytes.split(',').filter { it.isNotBlank() }.map { it.toInt().toByte() }.toByteArray(), Base64.URL_SAFE or Base64.NO_WRAP or Base64.NO_PADDING)
            synchronized(mintResults) { mintResults.remove(identifier) }?.complete(encoded)
        }

        @JavascriptInterface fun error(identifier: String, message: String) =
            synchronized(mintResults) { mintResults.remove(identifier) }?.completeExceptionally(IllegalStateException(message)) ?: Unit

        @JavascriptInterface fun initError(message: String) { ready.completeExceptionally(IllegalStateException(message)) }
    }

    private fun request(url: String, body: String): String {
        val media = "application/json+protobuf".toMediaType()
        val call = okhttp3.Request.Builder().url(url).post(body.toRequestBody(media))
            .header("User-Agent", USER_AGENT).header("Accept", "application/json")
            .header("x-goog-api-key", GOOGLE_API_KEY).header("x-user-agent", "grpc-web-javascript/0.1").build()
        return okhttp3.OkHttpClient().newCall(call).execute().use {
            check(it.isSuccessful) { "BotGuard HTTP ${it.code}" }
            it.body.string()
        }
    }

    private fun parseChallenge(raw: String): String {
        val outer = JSONArray(raw)
        val challenge = if (outer.length() > 1 && outer.opt(1) is String) JSONArray(descramble(outer.getString(1))) else outer.getJSONArray(0)
        fun firstString(array: JSONArray?): String? = array?.let { a -> (0 until a.length()).firstNotNullOfOrNull { a.opt(it) as? String } }
        return JSONObject().put("messageId", challenge.getString(0))
            .put("interpreterJavascript", JSONObject()
                .put("privateDoNotAccessOrElseSafeScriptWrappedValue", firstString(challenge.optJSONArray(1)))
                .put("privateDoNotAccessOrElseTrustedResourceUrlWrappedValue", firstString(challenge.optJSONArray(2))))
            .put("interpreterHash", challenge.getString(3)).put("program", challenge.getString(4))
            .put("globalName", challenge.getString(5)).put("clientExperimentsStateBlob", challenge.getString(7)).toString()
    }

    private fun descramble(value: String): String = decodeBase64(value).map { (it + 97).toByte() }.toByteArray().decodeToString()
    private fun decodeBase64(value: String): ByteArray = Base64.decode(value.replace('-', '+').replace('_', '/').replace('.', '='), Base64.DEFAULT)

    companion object {
        private const val GOOGLE_API_KEY = "AIzaSyDyT5W0Jh49F30Pqqtyfdf7pDLFKLJoAnw"
        private const val REQUEST_KEY = "O43z0dpjhgX20SCx4KAo"
        private const val CREATE_URL = "https://www.youtube.com/api/jnn/v1/Create"
        private const val GENERATE_URL = "https://www.youtube.com/api/jnn/v1/GenerateIT"
        private const val USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.3"
    }
}
